services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z_backend_service
    restart: always
    ports:
      - "5500:5500"
    env_file:
      - .env
    environment:
      - PORT=5500
      - NODE_ENV=production
